#!/bin/bash
usage(){
    echo "Usage: bamutils COMMAND"
    echo ""
    echo "Commands"
    echo "  DNA-seq"
    echo "    basecall      - Base caller"
    echo "    minorallele   - Find potential minor allele frequency"
    echo ""
    echo "  RNA-seq"
    echo "    cims          - Finds regions of unusual deletions (CLIP-seq)"
    echo "    rpkm          - Calculates RPKM/counts for genes/BED regions/repeats"
    echo ""
    echo "  General"
    echo "    check         - Checks a BAM file for corruption"
    echo "    convertregion - Converts region mapping to genomic mapping"
    echo "    export        - Export reads, mapped positions, and other fields (text)"
    echo "    expressed     - Finds regions expressed in a BAM file"
    echo "    extract       - Extracts reads based on regions in a BED file"
    echo "    filter        - Removes reads from a BAM file based on criteria"
    echo "    merge         - Combine multiple BAM files together (taking best-matches)"
    echo "    split         - Splits a BAM file into smaller pieces"
    echo "    stats         - Calculates simple stats for a BAM file"
    echo "    tag           - Update read names with a suffix (for merging)"
    echo ""
    echo "  Conversions"
    echo "    tobed        - Convert BAM reads to BED regions"
    echo "    tobedgraph   - Convert BAM coverage to BedGraph"
    echo "    tofasta      - Convert BAM reads to FASTA sequences"
    echo "                   (mapped or unmapped)"
    echo "    tofastq      - Convert BAM reads back to FASTQ sequences"
    echo "                   (mapped or unmapped)"
    echo ""
    echo "See 'bamutils help CMD' for more information about a specific command"
    echo -n "ngsutils "
    cat $DIR/VERSION
    echo ""
    exit -1
}

PREFIX="bam_"
SUBDIR="bam_utils"
REAL=`python -c 'import os,sys;print os.path.realpath(sys.argv[1])' "$0"`
DIR=`dirname "$REAL"`

source "$DIR"/common.sh
