#!/bin/bash
usage(){
    echo "Usage: bedutils COMMAND"
    echo ""
    echo "Commands"
    echo "  General"
    echo "    extend       - Extends BED regions (3' end)"
    echo "    reduce       - Merges overlapping BED regions"
    echo "    refcount     - Given a number of BED files, calculate the number of" 
    echo "                   samples that overlap regions in a reference BED file"
    echo "    sort         - Sorts a BED file (in place)"
    echo "    stats        - Calculates simple stats for a BED file"
    echo ""
    echo "  Conversions"
    echo "    fromprimers  - Converts a list of PCR primer pairs to BED regions"
    echo "    tobedgraph   - BED to BedGraph"
    echo "    tofasta      - Extract BED regions from a reference FASTA file"
    echo ""
    echo "See 'bedutils help CMD' for more information about a specific command"
    echo -n "ngsutils "
    cat $DIR/VERSION
    echo ""
    exit -1
}

PREFIX="bed_"
SUBDIR="bed_utils"
REAL=`python -c 'import os,sys;print os.path.realpath(sys.argv[1])' "$0"`
DIR=`dirname "$REAL"`

source "$DIR"/common.sh
