#!/bin/bash
usage(){
     echo "Usage: fastqutils COMMAND"
     echo ""
     echo "Commands"
     echo "    filter            - Filter out reads using a number of metrics"
     echo "    merge             - Merges paired FASTQ files into one file"
     echo "    names             - Write out the read names"
     echo "    split             - Splits a FASTQ file into N chunks"
     echo "    stats             - Calculate summary statistics for a FASTQ file"
     echo "    trim              - Remove 5' and 3' linker sequences (S/W aligned)"
     echo "    truncate          - Truncates reads to a maximum length"
     echo ""
     echo "Conversions"
     echo "    convertqual      - Converts qual values from Illumina to Sanger scale"
     echo "    fromfasta        - Converts FASTA/Qual files to FASTQ format"
     echo "    fromqseq         - Converts Illumina qseq (export/sorted) files to FASTQ"
     echo "    tofasta          - Converts to FASTA format (seq or qual)"
     echo ""
     echo "See 'fastqutils help CMD' for more information about a specific command"
     exit -1
}


REAL=`python -c 'import os,sys;print os.path.realpath(sys.argv[1])' "$0"`
DIR=`dirname "$REAL"`
PREFIX="fastq_"
SUBDIR="fastq_utils"

source "$DIR"/common.sh
