#!/bin/bash
usage(){
     echo "Usage: fastautils COMMAND"
     echo ""
     echo "Commands"
     echo "    to_fastq      - Converts FASTA/qual to FASTQ format"
     echo ""
     echo "See 'fastautils help CMD' for more information about a specific command"
     exit -1
}
 

REAL=`python -c 'import os,sys;print os.path.realpath(sys.argv[1])' "$0"`
DIR=`dirname "$REAL"`
PREFIX="fasta_"
SUBDIR="fasta_utils"

"$DIR"/build_deps.sh
if [ $? -ne 0 ]; then exit; fi

export PYTHONPATH=$PYTHONPATH:"$DIR":"$DIR"/ext

if [ -e "$DIR"/$SUBDIR/${PREFIX}$1.py ]; then
    source "$DIR"/common.sh
else
    "$DIR"/fasta_utils.py $@
fi
