#!/bin/bash
usage(){
    echo "Usage: gtfutils COMMAND"
    echo ""
    echo "Commands"
    echo "    genesize    - Extract genomic/transcript sizes for genes"
    echo "    junctions   - Build a junction library from FASTA and GFF/GTF model"
    echo ""
    echo "    tobed       - Converts a GFF/GTF model to BED format"
    echo "    addisoforms - Adds isoform data to a GFF/GTF file"
    echo ""
    echo "See 'gtfutils help CMD' for more information about a specific command"
    echo -n "ngsutils "
    cat $DIR/VERSION
    echo ""
    exit -1
}

PREFIX="gtf_"
SUBDIR="gtf_utils"
REAL=`python -c 'import os,sys;print os.path.realpath(sys.argv[1])' "$0"`
DIR=`dirname "$REAL"`

source "$DIR"/common.sh
