#!/bin/bash
usage(){
    echo "Usage: gtfutils COMMAND"
    echo ""
    echo "Commands"
    echo "    add_isoform - Appends isoform annotation from UCSC isoforms file"
    echo "    add_reflink - Appends isoform/name annotation from RefSeq/refLink"
    echo "    add_xref    - Appends name annotation from UCSC Xref file"
    echo ""
    echo "    genesize    - Extract genomic/transcript sizes for genes"
    echo "    junctions   - Build a junction library from FASTA and GFF/GTF model"
    echo ""
    echo "    tobed       - Converts a GFF/GTF model to BED format"
    echo ""
    echo "See 'gtfutils help CMD' for more information about a specific command"
    echo -n "ngsutils "
    cat $DIR/VERSION
    echo ""
    exit -1
}

PREFIX="gtf_"
SUBDIR="gtf_utils"
REAL=`python -c 'import os,sys;print os.path.realpath(sys.argv[1])' "$0"`
DIR=`dirname "$REAL"`

source "$DIR"/common.sh
